server:
  port: 8080
spring:
  application:
    name: api-gateway
  config:
    import: "configserver:"


#
#
#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#    config-url: /v3/api-docs/swagger-config
#    urls:
#      - url: /api/auth/v3/api-docs
#        name: Auth Service
#        display-name: Auth Service
#      - url: /api/book/v3/api-docs
#        name: Book Service
#        display-name: Book Service
#      - url: /api/record/v3/api-docs
#        name: Library Service
#        display-name: Library Service

#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/api/user/**
#
#        - id: project-service
#          uri: lb://project-service
#          predicates:
#            - Path=/api/project/**
#
#        - id: task-service
#          uri: lb://task-service
#          predicates:
#            - Path=/api/task/**