spring:
  datasource:
    username: postgres
    password: 1111
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost